In [1]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) # array attribute returns the tuple consisting of array dimensions.
b = np.array([6,3,2,8,5,7])
print("First np array\n",a)
print("Second np array\n",b)

First np array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second np array
 [6 3 2 8 5 7]


In [2]:
np.zeros((2,2))  #create an array of zeros

array([[0., 0.],
       [0., 0.]])

In [3]:
np.ones((2,2))  #create an array of ones

array([[1., 1.],
       [1., 1.]])

In [4]:
new_arr = np.arange(1,10,2)     #create an array of range with step values(2)
new_arr

array([1, 3, 5, 7, 9])

In [5]:
arr = np.arange(1,10,3)   #create an array of range with step values(3)
arr

array([1, 4, 7])

In [6]:
np.full((3,3),5)   #create an array of constant value i.e 5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [7]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [8]:
np.eye(3)     #create an 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.save('my_array',a)  #save the numpy array

In [10]:
np.load('my_array.npy')  #load numpy array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a.shape #tuple of array dimensions.

(3, 3)

In [12]:
np.sqrt(a)   #returns square root of each elements in aray

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [13]:
a.sum()

45

In [14]:
a.min()

1

In [15]:
a.max()

9

In [16]:
a.mean()

5.0

In [17]:
arr1 = a.view()   #create a view of the array with the same data
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
cp_arr = np.copy(a)    #create a copy of the array
cp_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<h3>Slicing & Subsetting</h3>

In [19]:
a[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a[1:2]

array([[4, 5, 6]])

In [22]:
a[::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [23]:
a[0][2]

3

In [24]:
a[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

<h3>Other numpy array functions</h3>

In [25]:
trans_arr = np.transpose(a)  #create a transpose of an array
trans_arr

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [26]:
b.reshape(6,-1)   #reshape the data

array([[6],
       [3],
       [2],
       [8],
       [5],
       [7]])

In [27]:
b.reshape(1,-1)

array([[6, 3, 2, 8, 5, 7]])

In [28]:
arr_new = np.array([3,2,1,6,7,8,4,9])
arr_new

array([3, 2, 1, 6, 7, 8, 4, 9])

In [29]:
arr_new.resize((1,8))   #resize a array with new shape
arr_new

array([[3, 2, 1, 6, 7, 8, 4, 9]])

In [30]:
nw1 = np.insert(arr_new,5,0)   #insert item to an array at specified index
nw1

array([3, 2, 1, 6, 7, 0, 8, 4, 9])

In [31]:
nw = np.delete(arr_new,[1])
nw

array([3, 1, 6, 7, 8, 4, 9])

In [32]:
np.concatenate((nw1,nw),axis=0)  #concatenates the two array

array([3, 2, 1, 6, 7, 0, 8, 4, 9, 3, 1, 6, 7, 8, 4, 9])

In [33]:
np.hstack(a)   #create a stack arrays horizontally

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.vstack(a)  #create a stack arrays vertically

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
np.column_stack(arr_new)    #creates a column stacked array

array([[3],
       [2],
       [1],
       [6],
       [7],
       [8],
       [4],
       [9]])